[mypy]
python_version = 3.10
exclude = (?x)(^\.venv/)
files = battle.py, capacitor.py, tournament.py, ex0, ex1, ex2
warn_unused_configs = True
check_untyped_defs = True
disallow_untyped_defs = True
no_implicit_optional = True
